### ISSUE TITLE
[KRM] Cloud Factory

### ISSUE THREAD

**Issue by nlamirault** [portefaix/portefaix-kubernetes#991]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**
Manage Cloud Providers resources  using Kubernetes Resource Model:

```[tasklist]
### Tasks
- [ ] https://github.com/portefaix/portefaix-kubernetes/issues/2807
- [ ] https://github.com/portefaix/portefaix-kubernetes/issues/2806
- [ ] https://github.com/portefaix/portefaix-kubernetes/issues/2805
- [ ] https://github.com/portefaix/portefaix-kubernetes/issues/2804
- [ ] https://github.com/portefaix/portefaix-kubernetes/issues/5749
- [ ] https://github.com/portefaix/portefaix-kubernetes/issues/5750
- [ ] https://github.com/portefaix/portefaix-kubernetes/issues/5751
- [ ] https://github.com/portefaix/portefaix-kubernetes/issues/3644
- [ ] https://github.com/portefaix/portefaix-kubernetes/issues/3645
- [ ] https://github.com/portefaix/portefaix-kubernetes/issues/3643
```
